<?xml version='1.0' standalone='yes'?>

<!-- Site pour faire la vÃ©rification de la DTD : http://www.xmlvalidation.com -->
<!DOCTYPE routing [
        <!ELEMENT routing (route*)>
        <!ELEMENT route (path, controller, action,operation?,valeur1?, valeur2?)>
        <!ELEMENT path (#PCDATA)>
        <!ELEMENT controller (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT operation (#PCDATA)>
        <!ELEMENT valeur1 (#PCDATA)>
        <!ELEMENT valeur2 (#PCDATA)>
        ]>

<routing>


    <route>
        <path>/</path>
        <controller>Home</controller>
        <action>home</action>
    </route>

    <route>
        <path>/home</path>
        <controller>Home</controller>
        <action>home</action>
    </route>

    <route>
        <path>/pathologies</path>
        <controller>Patho</controller>
        <action>getAll</action>
    </route>

    <route>
        <path>/calculatrice/{operation}/{valeur1}/{valeur2}</path>
        <controller>Calculatrice</controller>
        <action>calcul</action>
        <operation>(addition|soustraction|division|multiplication)</operation>
        <valeur1>(\d+)</valeur1>
        <valeur2>(\d+)</valeur2>
    </route>

    <route>
        <path>/404</path>
        <controller>Error</controller>
        <action>error_404</action>
    </route>

</routing>
